import pathlib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from typing import Union, Tuple
import re


class QuestionnaireAnalysis:
    """
    Reads and analyzes data generated by the questionnaire experiment.
    Should be able to accept strings and pathlib.Path objects.
    """

    def __init__(self, data_fname: Union[pathlib.Path, str]):
        if isinstance(data_fname, pathlib.Path):
            self.data_fname = data_fname
        else:
            self.data_fname = pathlib.Path(data_fname)
        if not (self.data_fname.exists() and self.data_fname.is_file()):
                raise ValueError("File does not exist")

    def read_data(self):
        """
        Reads the json data located in self.data_fname into memory, to
        the attribute self.data.
        """
        with open(self.data_fname, mode='r') as fid:
            self.data = pd.read_json(fid)

    def show_age_distrib(self) -> Tuple[np.ndarray, np.ndarray]:
        """
        Calculates and plots the age distribution of the participants.
        Returns a tuple containing two numpy arrays:
        The first item being the number of people in a given bin.
        The second item being the bin edges.
        """
        ages = np.array(self.data['age'])
        ages = ages[~np.isnan(ages)]
        distribution = plt.hist(ages, bins=10, range=(0.0, 100.0))
        plt.ylabel('Number of subjects')
        plt.xlabel('Age Groups')
        plt.title('Number of subjects per age group')
        plt.show()
        ans = (distribution[0],distribution[1])
        return ans

        #return np.histogram(a, bins=10, range=(0.0, 100.0))
    def check_if_email_is_valid(self,email) -> bool:
        pattern = re.compile(r"\"?([-a-zA-Z0-9.`?{}]+@\w+\.\w+)\"?")
        if not re.match(pattern, email):
            return False
        else:
            return True


    def remove_rows_without_mail(self) -> pd.DataFrame:
        """
        Checks self.data for rows with invalid emails, and removes them.
        Returns the corrected DataFrame, i.e. the same table but with
        the erroneous rows removed and the (ordinal) index after a reset.
        """
        self.data.dropna(axis=0, subset=['email'])
        self.data['is_valid_email'] = self.data['email'].apply(lambda x: self.check_if_email_is_valid(x))
        self.data = self.data[self.data.is_valid_email == True]
        return self.data.reset_index()


    def fill_na_with_mean(self) -> Union[pd.DataFrame, np.ndarray]:
        """
        Finds, in the original DataFrame, the subjects that didn't answer
        all questions, and replaces that missing value with the mean of the
        other grades for that student. Returns the corrected DataFrame,
        as well as the row indices of the students that their new grades
        were generated.
        """

        booleans = self.data.loc[:, 'q1':'q5'].isna().any(axis=1)
        self.data.loc[:, 'q1':'q5'].fillna(self.data.loc[:, 'q1':'q5'].mean(axis=1))
        generated_indices = np.where(booleans)
        return self.data, np.array(generated_indices)[0]

    def correlate_gender_age(self) -> pd.DataFrame:
        """
        Looks for a correlation between the gender of the subject, their age
        and the score for all five questions.
        Returns a DataFrame with a MultiIndex containing the gender and whether
        the subject is above 40 years of age, and the average score in each of
        the five questions.
        """



# if __name__ == "__main__":
#     fname = Path('C:\\Users\Ka\Desktop\Inbal\Python\hw5_2019-master\data.json')
#     truth = pd.read_csv('tests_data/q4_corr.csv').set_index(['gender', 'age'])
#     q = QuestionnaireAnalysis(fname)
#     q.read_data()
#     print(truth)



